sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t eajazali87/docker-react:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true eajazali87/docker-react npm run test
